version: 2
updates:
  - package-ecosystem: "terraform"
    directories:
      - "/"
      - "/modules/*/"
      # "/examples/*/" fails because the picofun lambdas aren't present in the repo.
    schedule:
      interval: "daily"
      time: "03:14"
      timezone: "Australia/Melbourne"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "terraform"

  - package-ecosystem: "uv"
    directories: 
      - "/scripts/backfill/"
      - "/modules/eventbus/"
      - "/modules/mock-ticket-update/"
      - "/modules/prepare-text/"
    schedule:
      interval: "daily"
      time: "03:44"
      timezone: "Australia/Melbourne"
    groups:
      boto3:
        patterns:
          - "*boto3*"
          - "botocore*"
      ruff-ty:
        patterns:
          # These are some of the fastest moving dependencies. Grouping to make my life easier.
          # They regularly have updates and so cause merge conflict.
          - "ruff"
          - "ty"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "python"